# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
              [5,2.4,3.7]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[7, 8, 9],
                [10, 11, 12],
                [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

a2_table = pd.DataFrame(a2)
a2_table

0    1    2
0  1.0  2.0  3.0
1  5.0  2.4  3.7

In [17]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3
arr_range = np.arange(0,10,3)
arr_range

array([0, 3, 6, 9])

In [22]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10, size=(7,2))
random_array

array([[9, 2],
       [2, 0],
       [0, 1],
       [1, 6],
       [7, 5],
       [6, 6],
       [3, 4]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_floats = np.random.random(size=(3,5))
random_array_floats

array([[0.01724019, 0.13279769, 0.74012598, 0.99597387, 0.77974133],
       [0.2751526 , 0.8460637 , 0.36640984, 0.87375874, 0.57211387],
       [0.7466139 , 0.44528783, 0.18245921, 0.67777005, 0.05152424]])

In [40]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr3 = np.random.randint(0,10, size=(4,6))
rand_arr3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?
###### > They are the same
Are the numbers in the array different or the same? Why do think this is?
###### > They are the same because of the used random seed. It acts like a key. When there is a set seed, the array will not get random number every time it runs

In [43]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr4 = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(rand_arr4)

array([1, 2, 3, 5, 7, 8, 9])

In [46]:
# Find the 0'th index of the latest array you created
rand_arr4[0]

array([2, 5, 8, 9, 9, 1, 9])

In [48]:
# Get the first 2 rows of latest array you created
rand_arr4[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr4[:2, :2]

array([[2, 5],
       [7, 9]])

In [54]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

rand_arr5 = np.random.randint(0,10, size=(3,5))
arrOnes = np.ones((3,5))

In [75]:
# Add the two arrays together
other_most_recent = rand_arr5 + arrOnes

In [62]:
# Create another array of ones of shape (5, 3)
arrOnes2 = np.ones((5,3))
arrOnes2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
# Try add the array of ones and the other most recent array together
arrOnes2 + arrOnes

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?
##### > It cannot support broadcasting because they are in a different shape
How would you fix it?
##### > Transpose the other array so the inner dimension will match

In [64]:
# Create another array of ones of shape (3, 5)
arrOnes3 = np.ones((3,5))

In [76]:
# Subtract the new array of ones from the other most recent array
arrOnes3 - other_most_recent

array([[-4., -3., -7., -6., -1.],
       [-3., -5., -8., -4., -6.],
       [-3., -9., -2.,  0., -4.]])

In [77]:
# Multiply the ones array with the latest array
arrOnes * arrOnes3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
# Take the latest array to the power of 2 using '**'
arrOnes3 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
# Do the same thing with np.square()
np.square(arrOnes3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
# Find the mean of the latest array using np.mean()
np.mean(arrOnes3)

1.0

In [81]:
# Find the maximum of the latest array using np.max()
np.max(arrOnes3)

1.0

In [82]:
# Find the minimum of the latest array using np.min()
np.min(arrOnes3)

1.0

In [83]:
# Find the standard deviation of the latest array
np.std(arrOnes3)

0.0

In [84]:
# Find the variance of the latest array
np.var(arrOnes3)

0.0

In [85]:
# Reshape the latest array to (3, 5, 1)
arrOnes3.reshape((3,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [86]:
# Transpose the latest array
arrOnes3.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?
##### >it switches the axes. In other terms, it switches the columns and rows. 

In [87]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_arr6 = np.random.randint(0,10, size=(3,3))
rand_arr7= np.random.randint(0,10, size=(3,2))


In [88]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_arr6, rand_arr7)

array([[ 43,  41],
       [ 89, 100],
       [136, 157]])

In [90]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

rand_arr8 = np.random.randint(0,10, size=(4,3))
rand_arr9= np.random.randint(0,10, size=(4,3))

In [91]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_arr8, rand_arr9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?
##### > Transpose the other array

In [93]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rand_arr8, rand_arr9.T)

array([[  3,  92, 102,  74],
       [ 15,  42,  20,  40],
       [ 12,  99,  92,  69],
       [ 12,  95,  88,  81]])

Notice how performing a transpose allows the dot product to happen.

Why is this?
> When using the dot product, the inner dimensions has to be the same.

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [94]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

Comparison_arr1 = np.random.randint(0,10,size=(2,3))
Comparison_arr2 = np.random.randint(0,10,size=(2,3))

In [95]:
# Compare the two arrays with '>'
Comparison_arr1 > Comparison_arr2

array([[False, False,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`? 
###### > It provides the boolean result if the statement is true depending on items

In [96]:
# Compare the two arrays with '>='
Comparison_arr1 >= Comparison_arr2

array([[False, False,  True],
       [False, False, False]])

In [97]:
# Find which elements of the first array are greater than 7
Comparison_arr1 > 7

array([[False, False, False],
       [False, False, False]])

In [98]:
# Which parts of each array are equal? (try using '==')
Comparison_arr1 > Comparison_arr2

array([[False, False,  True],
       [False, False, False]])

In [104]:
# Sort one of the arrays you just created in ascending order
np.sort(Comparison_arr1)

array([[3, 4, 6],
       [0, 1, 4]])

In [105]:
# Sort the indexes of one of the arrays you just created
np.argsort(Comparison_arr1)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [106]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(Comparison_arr1)

2

In [107]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(Comparison_arr1)

3

In [109]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(Comparison_arr1, axis=1)

array([2, 2], dtype=int64)

In [110]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(Comparison_arr1, axis=0)

array([1, 1, 1], dtype=int64)

In [111]:
# Create an array of normally distributed random numbers
normally_dist = np.random.normal(0,10,size=(5,3))
normally_dist

array([[  6.95119605, -20.33466546,  -1.89469265],
       [ -0.77218665,   8.24703005,  12.48212921],
       [ -4.03892269, -13.84518667,  13.67235424],
       [ 12.17885633,  -4.62005348,   3.50888494],
       [  3.81866234,   5.66275441,   2.04207979]])

In [117]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced = np.linspace(1, 100, 10)
evenly_spaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions
For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.